# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create working directory
WORKDIR /app

# Copy package installation files
COPY package*.json ./
COPY tsconfig.json ./

# Install only production dependencies, but since we need build tools, install dev deps as well
RUN npm install --ignore-scripts

# Copy the rest of the application source
COPY . .

# Build the application
RUN npm run build

# Expose necessary port if needed (not specified, so we'll run in stdio mode)

# Run the server
CMD [ "node", "build/index.js" ]
